//RM: 558062 - NOME: HENRIQUE FRANCISCO GARCIA - TURMA: 1TDSPK
//RM: 558843 - NOME: LAURA CINTRA - TURMA: 1TDSPK
//RM: 557197 - NOME: LARISSA MUNIZ - TUMR: 1TDSPK

//DROP DE TODAS TABELAS J? NA ORDEM
DROP TABLE t_pecas;
DROP TABLE t_telefone;
DROP TABLE t_endereco;
DROP TABLE t_oficina;
DROP TABLE t_orcamento;
DROP TABLE t_veiculo;
DROP TABLE t_diagnostico;
DROP TABLE t_historico;
DROP TABLE t_cliente;

//TABELAS NA ORDEM DE CRIA??O
//AP?S CRIAR AS TABELAS CERTIFIQUE-SE DE ADCIONAR OS ELEMENTOS EM ORDEM, POIS MUITOS TEM CHAVES ESTRANGEIRAS E UNICA
CREATE TABLE t_oficina (
   id_oficina INTEGER GENERATED BY DEFAULT AS IDENTITY,
   nome_fantasia VARCHAR(200) NOT NULL,
   cpf_cnpj_oficina VARCHAR(15) NOT NULL,
   servicos VARCHAR(200) NOT NULL,
   CONSTRAINT t_oficina_chave_primaria PRIMARY KEY (id_oficina),
   CONSTRAINT t_oficina_cpf_unico UNIQUE (cpf_cnpj_oficina)
);

----------------------------------------------------------------------------------------------------   
CREATE TABLE t_cliente (
   id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY,
   nome_cliente VARCHAR(50)NOT NULL,
   email_cliente VARCHAR(50)NOT NULL,
   senha_cliente VARCHAR(30)NOT NULL,
   cpf_cnpj_cliente VARCHAR(11) NOT NULL,
   CONSTRAINT t_cliente_chave_primaria PRIMARY KEY (id_cliente),
   CONSTRAINT t_cliente_cpf_unico UNIQUE (cpf_cnpj_cliente)
);

----------------------------------------------------------------------------------------------------
CREATE TABLE t_endereco (
   id_endereco INTEGER GENERATED BY DEFAULT AS IDENTITY,
   rua VARCHAR(50)NOT NULL,
   cep VARCHAR(8)NOT NULL,
   bairro VARCHAR(50)NOT NULL,
   cidade VARCHAR(50)NOT NULL,
   regiao VARCHAR(50)NOT NULL,
   estado CHAR(2)NOT NULL,
   complemento VARCHAR(50)NOT NULL,
   numero VARCHAR(50)NOT NULL,
   id_cliente INTEGER NOT NULL,
   id_oficina INTEGER NOT NULL,
   CONSTRAINT t_endereco_t_cliente_fk FOREIGN KEY (id_cliente)REFERENCES t_cliente(id_cliente),
   CONSTRAINT t_endereco_t_oficina_fk FOREIGN KEY (id_oficina)REFERENCES t_oficina(id_oficina),
   CONSTRAINT t_endereco_chave_primaria PRIMARY KEY (id_endereco)
);

-----------------------------------------------------------------------------------------------------------

CREATE TABLE t_telefone (
   id_telefone INTEGER GENERATED BY DEFAULT AS IDENTITY,
   ddd VARCHAR(50)NOT NULL,
   numero VARCHAR(50)NOT NULL,
   id_cliente INTEGER NOT NULL,
   id_oficina INTEGER NOT NULL,
   CONSTRAINT t_telefone_t_cliente_fk FOREIGN KEY (id_cliente)REFERENCES t_cliente(id_cliente),
   CONSTRAINT t_telefone_t_oficina_fk FOREIGN KEY (id_oficina)REFERENCES t_oficina(id_oficina),
   CONSTRAINT t_telefone_chave_primaria PRIMARY KEY (id_telefone)
);

--------------------------------------------------------------------------------------------------------
CREATE TABLE t_veiculo (
   id_veiculo INTEGER GENERATED BY DEFAULT AS IDENTITY,
   placa VARCHAR(8)NOT NULL,
   modelo VARCHAR(15)NOT NULL,
   marca VARCHAR(15)NOT NULL,
   id_cliente INTEGER NOT NULL,
   CONSTRAINT t_veiculo_t_cliente_fk FOREIGN KEY (id_cliente)REFERENCES t_cliente(id_cliente),
   CONSTRAINT t_veiculo_chave_primaria PRIMARY KEY (id_veiculo)
);

----------------------------------------------------------------------------------------------------
CREATE TABLE t_diagnostico (
   id_diagnostico INTEGER GENERATED BY DEFAULT AS IDENTITY,
   perguntas VARCHAR(200)NOT NULL,
   respostas VARCHAR(200)NOT NULL,
   sugestoes VARCHAR(300)NOT NULL,
   id_veiculo INTEGER NOT NULL,
   CONSTRAINT t_diagnostico_t_veiculo_fk FOREIGN KEY (id_veiculo)REFERENCES t_veiculo(id_veiculo),
   CONSTRAINT t_diagnostico_chave_primaria PRIMARY KEY (id_diagnostico)
);

----------------------------------------------------------------------------------------------------
CREATE TABLE t_pecas (
   id_pecas INTEGER GENERATED BY DEFAULT AS IDENTITY,
   quantidade VARCHAR(200) NOT NULL,
   nome_da_peca VARCHAR(30) NOT NULL,
   funcao_peca VARCHAR(300) NOT NULL,
   valor_peca DECIMAL(8,2) NOT NULL,
   id_diagnostico INTEGER NOT NULL,
   CONSTRAINT t_pecas_chave_primaria PRIMARY KEY (id_pecas),
   CONSTRAINT t_pecas_t_diagnostico_fk FOREIGN KEY (id_diagnostico)REFERENCES t_diagnostico(id_diagnostico),
   CONSTRAINT t_diagnostico_valor_peca_ck CHECK (valor_peca > 0)
);

------------------------------------------------------------------------------------------------------------
CREATE TABLE t_historico (
   id_historico INTEGER GENERATED BY DEFAULT AS IDENTITY,
   sugestoes VARCHAR(200) NOT NULL,
   registros VARCHAR(200) NOT NULL,
   perguntas VARCHAR(200) NOT NULL,
   respostas VARCHAR(200) NOT NULL,
      id_cliente INTEGER NOT NULL,
   CONSTRAINT t_historico_chave_primaria PRIMARY KEY (id_historico),
   CONSTRAINT t_historico_t_cliente_fk FOREIGN KEY (id_cliente)REFERENCES t_cliente(id_cliente)
);

-------------------------------------------------------------------------------------------------------------
CREATE TABLE t_orcamento (
   id_orcamento INTEGER GENERATED BY DEFAULT AS IDENTITY,
   datao DATE,
   valor DECIMAL(8,2),
   id_veiculo INTEGER NOT NULL,
   CONSTRAINT t_orcamento_chave_primaria PRIMARY KEY (id_orcamento),
   CONSTRAINT t_orcamento_t_veiculo_fk FOREIGN KEY (id_veiculo)REFERENCES t_veiculo(id_veiculo),
   CONSTRAINT t_orcamento_valor_ck CHECK (valor > 0)
);

--------------------------------------------------------------------------------------------------------
//INSERINDO OS DADOS DAS TABELAS
//INSERINDO DADOS NA TABELA OFICINA
INSERT INTO t_oficina (nome_fantasia, cpf_cnpj_oficina, servicos) VALUES ('Oficina Central', '12345678901234', 'Troca de óleo');
INSERT INTO t_oficina (nome_fantasia, cpf_cnpj_oficina, servicos) VALUES ('Oficina Autos', '98765432109876', 'Alinhamento e balanceamento');
INSERT INTO t_oficina (nome_fantasia, cpf_cnpj_oficina, servicos) VALUES ('Mecânica Rápida', '11223344556677', 'Revisão completa');
INSERT INTO t_oficina (nome_fantasia, cpf_cnpj_oficina, servicos) VALUES ('Super Carros', '33445566778899', 'Pintura automotiva');
INSERT INTO t_oficina (nome_fantasia, cpf_cnpj_oficina, servicos) VALUES ('Oficina Bom Preço', '55667788990011', 'Troca de freios');
INSERT INTO t_oficina (nome_fantasia, cpf_cnpj_oficina, servicos) VALUES ('Auto Total', '66778899001122', 'Manutenção de suspensão');
INSERT INTO t_oficina (nome_fantasia, cpf_cnpj_oficina, servicos) VALUES ('Auto Mec', '77889900112233', 'Troca de embreagem');
INSERT INTO t_oficina (nome_fantasia, cpf_cnpj_oficina, servicos) VALUES ('Oficina Express', '88990011223344', 'Manutenção de motor');
INSERT INTO t_oficina (nome_fantasia, cpf_cnpj_oficina, servicos) VALUES ('Top Car Service', '99001122334455', 'Balanceamento');
INSERT INTO t_oficina (nome_fantasia, cpf_cnpj_oficina, servicos) VALUES ('Rodas & Motores', '10203040506070', 'Alinhamento 3D');
INSERT INTO t_oficina (nome_fantasia, cpf_cnpj_oficina, servicos) VALUES ('Mecânica do João', '11002200334455', 'Instalação de som');
INSERT INTO t_oficina (nome_fantasia, cpf_cnpj_oficina, servicos) VALUES ('Oficina Alfa', '22334455667788', 'Troca de bateria');
INSERT INTO t_oficina (nome_fantasia, cpf_cnpj_oficina, servicos) VALUES ('Beta Motors', '33445566778800', 'Troca de óleo e filtros');
INSERT INTO t_oficina (nome_fantasia, cpf_cnpj_oficina, servicos) VALUES ('Oficina Gamma', '44556677889900', 'Diagnóstico eletrônico');
INSERT INTO t_oficina (nome_fantasia, cpf_cnpj_oficina, servicos) VALUES ('Mecânica Delta', '55667788990022', 'Reparos em suspensão');
INSERT INTO t_oficina (nome_fantasia, cpf_cnpj_oficina, servicos) VALUES ('Oficina Suprema', '66778899001133', 'Revisão de 10 mil km');
INSERT INTO t_oficina (nome_fantasia, cpf_cnpj_oficina, servicos) VALUES ('Oficina Master', '77889900112244', 'Troca de velas');
INSERT INTO t_oficina (nome_fantasia, cpf_cnpj_oficina, servicos) VALUES ('Pit Stop', '88990011223355', 'Substituição de amortecedores');
INSERT INTO t_oficina (nome_fantasia, cpf_cnpj_oficina, servicos) VALUES ('Oficina Real', '99001122334466', 'Troca de filtros de ar');
INSERT INTO t_oficina (nome_fantasia, cpf_cnpj_oficina, servicos) VALUES ('Auto Serviços', '10203040506080', 'Instalação de alarme');

//INSERINDO DADOS NA TABELA CLIENTE
INSERT INTO t_cliente (nome_cliente, email_cliente, senha_cliente, cpf_cnpj_cliente) VALUES ('João Silva', 'joao.silva@email.com', 'senha123', '12345678901');
INSERT INTO t_cliente (nome_cliente, email_cliente, senha_cliente, cpf_cnpj_cliente) VALUES ('Maria Santos', 'maria.santos@email.com', 'senha456', '23456789012');
INSERT INTO t_cliente (nome_cliente, email_cliente, senha_cliente, cpf_cnpj_cliente) VALUES ('Carlos Almeida', 'carlos.almeida@email.com', 'senha789', '34567890123');
INSERT INTO t_cliente (nome_cliente, email_cliente, senha_cliente, cpf_cnpj_cliente) VALUES ('Ana Souza', 'ana.souza@email.com', 'senha012', '45678901234');
INSERT INTO t_cliente (nome_cliente, email_cliente, senha_cliente, cpf_cnpj_cliente) VALUES ('Paulo Pereira', 'paulo.pereira@email.com', 'senha345', '56789012345');
INSERT INTO t_cliente (nome_cliente, email_cliente, senha_cliente, cpf_cnpj_cliente) VALUES ('Fernanda Lima', 'fernanda.lima@email.com', 'senha678', '67890123456');
INSERT INTO t_cliente (nome_cliente, email_cliente, senha_cliente, cpf_cnpj_cliente) VALUES ('Lucas Araújo', 'lucas.araujo@email.com', 'senha910', '78901234567');
INSERT INTO t_cliente (nome_cliente, email_cliente, senha_cliente, cpf_cnpj_cliente) VALUES ('Bruna Costa', 'bruna.costa@email.com', 'senha101', '89012345678');
INSERT INTO t_cliente (nome_cliente, email_cliente, senha_cliente, cpf_cnpj_cliente) VALUES ('Gabriel Nunes', 'gabriel.nunes@email.com', 'senha121', '90123456789');
INSERT INTO t_cliente (nome_cliente, email_cliente, senha_cliente, cpf_cnpj_cliente) VALUES ('Roberto Dias', 'roberto.dias@email.com', 'senha131', '01234567890');
INSERT INTO t_cliente (nome_cliente, email_cliente, senha_cliente, cpf_cnpj_cliente) VALUES ('Juliana Barros', 'juliana.barros@email.com', 'senha141', '11234567890');
INSERT INTO t_cliente (nome_cliente, email_cliente, senha_cliente, cpf_cnpj_cliente) VALUES ('Pedro Gonçalves', 'pedro.goncalves@email.com', 'senha151', '22345678901');
INSERT INTO t_cliente (nome_cliente, email_cliente, senha_cliente, cpf_cnpj_cliente) VALUES ('Camila Martins', 'camila.martins@email.com', 'senha161', '33456789012');
INSERT INTO t_cliente (nome_cliente, email_cliente, senha_cliente, cpf_cnpj_cliente) VALUES ('Felipe Borges', 'felipe.borges@email.com', 'senha171', '44567890123');
INSERT INTO t_cliente (nome_cliente, email_cliente, senha_cliente, cpf_cnpj_cliente) VALUES ('Larissa Carvalho', 'larissa.carvalho@email.com', 'senha181', '55678901234');
INSERT INTO t_cliente (nome_cliente, email_cliente, senha_cliente, cpf_cnpj_cliente) VALUES ('Marcelo Fernandes', 'marcelo.fernandes@email.com', 'senha191', '66789012345');
INSERT INTO t_cliente (nome_cliente, email_cliente, senha_cliente, cpf_cnpj_cliente) VALUES ('Renata Monteiro', 'renata.monteiro@email.com', 'senha201', '77890123456');
INSERT INTO t_cliente (nome_cliente, email_cliente, senha_cliente, cpf_cnpj_cliente) VALUES ('Thiago Ribeiro', 'thiago.ribeiro@email.com', 'senha211', '88901234567');
INSERT INTO t_cliente (nome_cliente, email_cliente, senha_cliente, cpf_cnpj_cliente) VALUES ('André Freitas', 'andre.freitas@email.com', 'senha221', '99012345678');
INSERT INTO t_cliente (nome_cliente, email_cliente, senha_cliente, cpf_cnpj_cliente) VALUES ('Isabela Moraes', 'isabela.moraes@email.com', 'senha231', '10123456789');

//INSERINDO DADOS NA TABELA ENDERECO
INSERT INTO t_endereco (rua, cep, bairro, cidade, regiao, estado, complemento, numero, id_cliente, id_oficina) VALUES ('Rua das Flores', '12345678', 'Centro', 'São Paulo', 'Sudeste', 'SP', 'Apto 101', '100', 1, 1);
INSERT INTO t_endereco (rua, cep, bairro, cidade, regiao, estado, complemento, numero, id_cliente, id_oficina) VALUES ('Av. Brasil', '23456789', 'Jardins', 'Rio de Janeiro', 'Sudeste', 'RJ', 'Bloco B', '200', 2, 2);
INSERT INTO t_endereco (rua, cep, bairro, cidade, regiao, estado, complemento, numero, id_cliente, id_oficina) VALUES ('Rua XV de Novembro', '34567890', 'Centro', 'Curitiba', 'Sul', 'PR', 'Casa', '300', 3, 3);
INSERT INTO t_endereco (rua, cep, bairro, cidade, regiao, estado, complemento, numero, id_cliente, id_oficina) VALUES ('Rua das Palmeiras', '45678901', 'Boa Vista', 'Belo Horizonte', 'Sudeste', 'MG', 'Apto 202', '400',4, 4);
INSERT INTO t_endereco (rua, cep, bairro, cidade, regiao, estado, complemento, numero, id_cliente, id_oficina) VALUES ('Av. Sete de Setembro', '56789012', 'Liberdade', 'Salvador', 'Nordeste', 'BA', 'Bloco C', '500', 5, 5);
INSERT INTO t_endereco (rua, cep, bairro, cidade, regiao, estado, complemento, numero, id_cliente, id_oficina) VALUES ('Rua Augusta', '67890123', 'Consolação', 'São Paulo', 'Sudeste', 'SP', 'Casa', '600', 6, 6);
INSERT INTO t_endereco (rua, cep, bairro, cidade, regiao, estado, complemento, numero, id_cliente, id_oficina) VALUES ('Rua da Paz', '78901234', 'Alphaville', 'Barueri', 'Sudeste', 'SP', 'Apto 303', '700', 7, 7);
INSERT INTO t_endereco (rua, cep, bairro, cidade, regiao, estado, complemento, numero, id_cliente, id_oficina) VALUES ('Rua Rio Branco', '89012345', 'Centro', 'Recife', 'Nordeste', 'PE', 'Bloco D', '800', 8, 8);
INSERT INTO t_endereco (rua, cep, bairro, cidade, regiao, estado, complemento, numero, id_cliente, id_oficina) VALUES ('Av. Beira Mar', '90123456', 'Praia', 'Fortaleza', 'Nordeste', 'CE', 'Casa', '900', 9, 9);
INSERT INTO t_endereco (rua, cep, bairro, cidade, regiao, estado, complemento, numero, id_cliente, id_oficina) VALUES ('Rua da Glória', '01234567', 'Centro', 'Manaus', 'Norte', 'AM', 'Apto 404', '1000', 10, 10);
INSERT INTO t_endereco (rua, cep, bairro, cidade, regiao, estado, complemento, numero, id_cliente, id_oficina) VALUES ('Rua da Estrela', '11234567', 'Centro', 'Florianópolis', 'Sul', 'SC', 'Casa', '1100', 11, 11);
INSERT INTO t_endereco (rua, cep, bairro, cidade, regiao, estado, complemento, numero, id_cliente, id_oficina) VALUES ('Av. das Nações', '12345670', 'Asa Sul', 'Brasília', 'Centro-Oeste', 'DF', 'Apto 505', '1200', 12, 12);
INSERT INTO t_endereco (rua, cep, bairro, cidade, regiao, estado, complemento, numero, id_cliente, id_oficina) VALUES ('Rua do Comércio', '13456780', 'Centro', 'Porto Alegre', 'Sul', 'RS', 'Bloco E', '1300', 13, 13);
INSERT INTO t_endereco (rua, cep, bairro, cidade, regiao, estado, complemento, numero, id_cliente, id_oficina) VALUES ('Av. Paulista', '14567890', 'Bela Vista', 'São Paulo', 'Sudeste', 'SP', 'Apto 606', '1400', 14, 14);
INSERT INTO t_endereco (rua, cep, bairro, cidade, regiao, estado, complemento, numero, id_cliente, id_oficina) VALUES ('Rua do Passeio', '15678901', 'Centro', 'Belém', 'Norte', 'PA', 'Casa', '1500', 15, 15);
INSERT INTO t_endereco (rua, cep, bairro, cidade, regiao, estado, complemento, numero, id_cliente, id_oficina) VALUES ('Rua das Acácias', '16789012', 'Zona Sul', 'São Paulo', 'Sudeste', 'SP', 'Bloco F', '1600', 16, 16);
INSERT INTO t_endereco (rua, cep, bairro, cidade, regiao, estado, complemento, numero, id_cliente, id_oficina) VALUES ('Av. Oceânica', '17890123', 'Orla', 'Natal', 'Nordeste', 'RN', 'Apto 707', '1700', 17, 17);
INSERT INTO t_endereco (rua, cep, bairro, cidade, regiao, estado, complemento, numero, id_cliente, id_oficina) VALUES ('Rua Dom Pedro', '18901234', 'Centro', 'São Luís', 'Nordeste', 'MA', 'Casa', '1800', 18, 18);
INSERT INTO t_endereco (rua, cep, bairro, cidade, regiao, estado, complemento, numero, id_cliente, id_oficina) VALUES ('Rua das Laranjeiras', '19012345', 'Zona Norte', 'Rio de Janeiro', 'Sudeste', 'RJ', 'Bloco G', '1900', 19, 19);
INSERT INTO t_endereco (rua, cep, bairro, cidade, regiao, estado, complemento, numero, id_cliente, id_oficina) VALUES ('Av. do Contorno', '20123456', 'Centro', 'Goiânia', 'Centro-Oeste', 'GO', 'Apto 808', '2000', 20, 20);

//INSERINDO DADOS NA TABELA TELEFONE
INSERT INTO t_telefone (ddd, numero, id_cliente, id_oficina) VALUES ('11', '987654321', 1, 1);
INSERT INTO t_telefone (ddd, numero, id_cliente, id_oficina) VALUES ('21', '988765432', 2, 2);
INSERT INTO t_telefone (ddd, numero, id_cliente, id_oficina) VALUES ('41', '977654321', 3, 3);
INSERT INTO t_telefone (ddd, numero, id_cliente, id_oficina) VALUES ('31', '966543210', 4, 4);
INSERT INTO t_telefone (ddd, numero, id_cliente, id_oficina) VALUES ('71', '955432109', 5, 5);
INSERT INTO t_telefone (ddd, numero, id_cliente, id_oficina) VALUES ('11', '944321098', 6, 6);
INSERT INTO t_telefone (ddd, numero, id_cliente, id_oficina) VALUES ('21', '933210987', 7, 7);
INSERT INTO t_telefone (ddd, numero, id_cliente, id_oficina) VALUES ('81', '922109876', 8, 8);
INSERT INTO t_telefone (ddd, numero, id_cliente, id_oficina) VALUES ('85', '911098765', 9, 9);
INSERT INTO t_telefone (ddd, numero, id_cliente, id_oficina) VALUES ('92', '900987654', 10, 10);
INSERT INTO t_telefone (ddd, numero, id_cliente, id_oficina) VALUES ('48', '988876543', 11, 11);
INSERT INTO t_telefone (ddd, numero, id_cliente, id_oficina) VALUES ('61', '977765432', 12, 12);
INSERT INTO t_telefone (ddd, numero, id_cliente, id_oficina) VALUES ('51', '966654321', 13, 13);
INSERT INTO t_telefone (ddd, numero, id_cliente, id_oficina) VALUES ('11', '955543210', 14, 14);
INSERT INTO t_telefone (ddd, numero, id_cliente, id_oficina) VALUES ('91', '944432109', 15, 15);
INSERT INTO t_telefone (ddd, numero, id_cliente, id_oficina) VALUES ('11', '933321098', 16, 16);
INSERT INTO t_telefone (ddd, numero, id_cliente, id_oficina) VALUES ('84', '922210987', 17, 17);
INSERT INTO t_telefone (ddd, numero, id_cliente, id_oficina) VALUES ('98', '911109876', 18, 18);
INSERT INTO t_telefone (ddd, numero, id_cliente, id_oficina) VALUES ('21', '900098765', 19, 19);
INSERT INTO t_telefone (ddd, numero, id_cliente, id_oficina) VALUES ('62', '988987654', 20, 20);

//INSERINDO DADOS NA TABELA VEICULO
INSERT INTO t_veiculo (placa, modelo, marca, id_cliente) VALUES ('ABC1234', 'Civic', 'Honda', 1);
INSERT INTO t_veiculo (placa, modelo, marca, id_cliente) VALUES ('DEF5678', 'Corolla', 'Toyota', 2);
INSERT INTO t_veiculo (placa, modelo, marca, id_cliente) VALUES ('GHI9012', 'Gol', 'Volkswagen', 3);
INSERT INTO t_veiculo (placa, modelo, marca, id_cliente) VALUES ('JKL3456', 'Polo', 'Volkswagen', 4);
INSERT INTO t_veiculo (placa, modelo, marca, id_cliente) VALUES ('MNO7890', 'Fiesta', 'Ford', 5);
INSERT INTO t_veiculo (placa, modelo, marca, id_cliente) VALUES ('PQR1234', 'Onix', 'Chevrolet', 6);
INSERT INTO t_veiculo (placa, modelo, marca, id_cliente) VALUES ('STU5678', 'HB20', 'Hyundai', 7);
INSERT INTO t_veiculo (placa, modelo, marca, id_cliente) VALUES ('VWX9012', 'EcoSport', 'Ford', 8);
INSERT INTO t_veiculo (placa, modelo, marca, id_cliente) VALUES ('YZA3456', 'Cruze', 'Chevrolet', 9);
INSERT INTO t_veiculo (placa, modelo, marca, id_cliente) VALUES ('BCD7890', 'Renegade', 'Jeep', 10);
INSERT INTO t_veiculo (placa, modelo, marca, id_cliente) VALUES ('EFG1234', 'Compass', 'Jeep', 11);
INSERT INTO t_veiculo (placa, modelo, marca, id_cliente) VALUES ('HIJ5678', 'Sandero', 'Renault', 12);
INSERT INTO t_veiculo (placa, modelo, marca, id_cliente) VALUES ('KLM9012', 'Duster', 'Renault', 13);
INSERT INTO t_veiculo (placa, modelo, marca, id_cliente) VALUES ('NOP3456', 'Fit', 'Honda', 14);
INSERT INTO t_veiculo (placa, modelo, marca, id_cliente) VALUES ('QRS7890', 'Civic', 'Honda', 15);
INSERT INTO t_veiculo (placa, modelo, marca, id_cliente) VALUES ('TUV1234', 'Corolla', 'Toyota', 16);
INSERT INTO t_veiculo (placa, modelo, marca, id_cliente) VALUES ('WXY5678', 'Polo', 'Volkswagen', 17);
INSERT INTO t_veiculo (placa, modelo, marca, id_cliente) VALUES ('ZAB9012', 'Gol', 'Volkswagen', 18);
INSERT INTO t_veiculo (placa, modelo, marca, id_cliente) VALUES ('CDE3456', 'Onix', 'Chevrolet', 19);
INSERT INTO t_veiculo (placa, modelo, marca, id_cliente) VALUES ('FGH7890', 'Cruze', 'Chevrolet', 20);

//INSERINDO DADOS NA TABELA DIAGNOSTICO
INSERT INTO t_diagnostico (perguntas, respostas, sugestoes, id_veiculo) VALUES ('Ar-condicionado está gelando?', 'Sim', 'Verificar o filtro do ar', 1);
INSERT INTO t_diagnostico (perguntas, respostas, sugestoes, id_veiculo) VALUES ('As luzes de painel estão acesas?', 'Não', 'Verificar os sensores', 2);
INSERT INTO t_diagnostico (perguntas, respostas, sugestoes, id_veiculo) VALUES ('O carro faz barulho ao acelerar?', 'Sim', 'Verificar o sistema de escapamento', 3);
INSERT INTO t_diagnostico (perguntas, respostas, sugestoes, id_veiculo) VALUES ('Os freios estão funcionando corretamente?', 'Não', 'Trocar as pastilhas de freio', 4);
INSERT INTO t_diagnostico (perguntas, respostas, sugestoes, id_veiculo) VALUES ('O motor está superaquecendo?', 'Sim', 'Verificar o nível de líquido de arrefecimento', 5);
INSERT INTO t_diagnostico (perguntas, respostas, sugestoes, id_veiculo) VALUES ('O carro está consumindo mais combustível?', 'Não', 'Verificar a injeção eletrônica', 6);
INSERT INTO t_diagnostico (perguntas, respostas, sugestoes, id_veiculo) VALUES ('As portas estão fechando corretamente?', 'Sim', 'Verificar as dobradiças', 7);
INSERT INTO t_diagnostico (perguntas, respostas, sugestoes, id_veiculo) VALUES ('A embreagem está funcionando?', 'Não', 'Verificar o fluido da embreagem', 8);
INSERT INTO t_diagnostico (perguntas, respostas, sugestoes, id_veiculo) VALUES ('As luzes de freio estão funcionando?', 'Sim', 'Verificar as lâmpadas', 9);
INSERT INTO t_diagnostico (perguntas, respostas, sugestoes, id_veiculo) VALUES ('O carro está tremendo ao dirigir?', 'Sim', 'Verificar o balanceamento das rodas', 10);
INSERT INTO t_diagnostico (perguntas, respostas, sugestoes, id_veiculo) VALUES ('A bateria está carregando?', 'Não', 'Verificar o alternador', 11);
INSERT INTO t_diagnostico (perguntas, respostas, sugestoes, id_veiculo) VALUES ('O ar quente está saindo do ar-condicionado?', 'Sim', 'Verificar o sistema de ar-condicionado', 12);
INSERT INTO t_diagnostico (perguntas, respostas, sugestoes, id_veiculo) VALUES ('Os pneus estão desgastados?', 'Não', 'Verificar o alinhamento', 13);
INSERT INTO t_diagnostico (perguntas, respostas, sugestoes, id_veiculo) VALUES ('O farol está funcionando?', 'Sim', 'Verificar a lâmpada', 14);
INSERT INTO t_diagnostico (perguntas, respostas, sugestoes, id_veiculo) VALUES ('A direção está pesada?', 'Não', 'Verificar o fluido da direção', 15);
INSERT INTO t_diagnostico (perguntas, respostas, sugestoes, id_veiculo) VALUES ('A suspensão está fazendo barulho?', 'Sim', 'Verificar os amortecedores', 16);
INSERT INTO t_diagnostico (perguntas, respostas, sugestoes, id_veiculo) VALUES ('O carro puxa para o lado ao dirigir?', 'Não', 'Verificar a pressão dos pneus', 17);
INSERT INTO t_diagnostico (perguntas, respostas, sugestoes, id_veiculo) VALUES ('Os cintos de segurança estão funcionando?', 'Sim', 'Verificar a fivela', 18);
INSERT INTO t_diagnostico (perguntas, respostas, sugestoes, id_veiculo) VALUES ('Os faróis estão regulados?', 'Não', 'Ajustar a altura dos faróis', 19);
INSERT INTO t_diagnostico (perguntas, respostas, sugestoes, id_veiculo) VALUES ('O carro tem cheiro de combustível?', 'Sim', 'Verificar o sistema de combustível', 20);

//INSERINDO DADOS NA TABELA PEÇAS
INSERT INTO t_pecas (quantidade, nome_da_peca, funcao_peca, valor_peca, id_diagnostico) VALUES ('2', 'Filtro de ar', 'Filtrar o ar que entra no motor', 150.00, 1);
INSERT INTO t_pecas (quantidade, nome_da_peca, funcao_peca, valor_peca, id_diagnostico) VALUES ('4', 'Pastilha de freio', 'Parar o carro ao acionar o freio', 200.00, 2);
INSERT INTO t_pecas (quantidade, nome_da_peca, funcao_peca, valor_peca, id_diagnostico) VALUES ('1', 'Bateria', 'Fornecer energia ao veículo', 450.00, 3);
INSERT INTO t_pecas (quantidade, nome_da_peca, funcao_peca, valor_peca, id_diagnostico) VALUES ('1', 'Disco de freio', 'Parar o carro ao acionar o freio', 300.00, 4);
INSERT INTO t_pecas (quantidade, nome_da_peca, funcao_peca, valor_peca, id_diagnostico) VALUES ('1', 'Radiador', 'Refrigerar o motor', 600.00, 5);
INSERT INTO t_pecas (quantidade, nome_da_peca, funcao_peca, valor_peca, id_diagnostico) VALUES ('1', 'Amortecedor', 'Absorver impactos e manter a estabilidade', 500.00, 6);
INSERT INTO t_pecas (quantidade, nome_da_peca, funcao_peca, valor_peca, id_diagnostico) VALUES ('1', 'Pneu', 'Proporcionar tração e estabilidade', 250.00, 7);
INSERT INTO t_pecas (quantidade, nome_da_peca, funcao_peca, valor_peca, id_diagnostico) VALUES ('1', 'Filtro de combustível', 'Filtrar impurezas do combustível', 80.00, 8);
INSERT INTO t_pecas (quantidade, nome_da_peca, funcao_peca, valor_peca, id_diagnostico) VALUES ('1', 'Sensor de óleo', 'Monitorar o nível de óleo', 120.00, 9);
INSERT INTO t_pecas (quantidade, nome_da_peca, funcao_peca, valor_peca, id_diagnostico) VALUES ('1', 'Cinto de segurança', 'Proteger ocupantes em caso de acidente', 70.00, 10);
INSERT INTO t_pecas (quantidade, nome_da_peca, funcao_peca, valor_peca, id_diagnostico) VALUES ('1', 'Lampada do farol', 'Iluminar o caminho durante a noite', 25.00, 11);
INSERT INTO t_pecas (quantidade, nome_da_peca, funcao_peca, valor_peca, id_diagnostico) VALUES ('1', 'Bico injetor', 'Misturar combustível e ar para combustão', 150.00, 12);
INSERT INTO t_pecas (quantidade, nome_da_peca, funcao_peca, valor_peca, id_diagnostico) VALUES ('1', 'Fusível', 'Proteger o sistema elétrico do carro', 5.00, 13);
INSERT INTO t_pecas (quantidade, nome_da_peca, funcao_peca, valor_peca, id_diagnostico) VALUES ('1', 'Válvula termostática', 'Controlar a temperatura do motor', 90.00, 14);
INSERT INTO t_pecas (quantidade, nome_da_peca, funcao_peca, valor_peca, id_diagnostico) VALUES ('1', 'Coxim do motor', 'Absorver vibrações do motor', 120.00, 15);
INSERT INTO t_pecas (quantidade, nome_da_peca, funcao_peca, valor_peca, id_diagnostico) VALUES ('1', 'Correia dentada', 'Sincronizar os componentes do motor', 150.00, 16);
INSERT INTO t_pecas (quantidade, nome_da_peca, funcao_peca, valor_peca, id_diagnostico) VALUES ('1', 'Óleo de motor', 'Lubrificar os componentes do motor', 100.00, 17);
INSERT INTO t_pecas (quantidade, nome_da_peca, funcao_peca, valor_peca, id_diagnostico) VALUES ('1', 'Filtro de cabine', 'Filtrar o ar que entra na cabine', 45.00, 18);
INSERT INTO t_pecas (quantidade, nome_da_peca, funcao_peca, valor_peca, id_diagnostico) VALUES ('1', 'Mangueira do radiador', 'Transportar o líquido de arrefecimento', 60.00, 19);
INSERT INTO t_pecas (quantidade, nome_da_peca, funcao_peca, valor_peca, id_diagnostico) VALUES ('1', 'Bomba d\água', 'Circular o líquido de arrefecimento', 200.00, 20);

//INSERINDO DADOS NA TABELA HISTORICO
INSERT INTO t_historico (sugestoes, registros, perguntas, respostas, id_cliente) VALUES ('Calibrar os pneus', 'Pneus estavam murchos', 'Pneus estão calibrados?', 'Não', 1);
INSERT INTO t_historico (sugestoes, registros, perguntas, respostas, id_cliente) VALUES ('Verificar o sistema de injeção', 'Carro consumindo muito combustível', 'O carro está consumindo mais combustível?', 'Sim', 2);
INSERT INTO t_historico (sugestoes, registros, perguntas, respostas, id_cliente) VALUES ('Trocar a bateria', 'Bateria estava fraca', 'Bateria está carregando?', 'Não', 3);
INSERT INTO t_historico (sugestoes, registros, perguntas, respostas, id_cliente) VALUES ('Trocar o disco de freio', 'Disco de freio estava desgastado', 'O carro faz barulho ao frear?', 'Sim', 4);
INSERT INTO t_historico (sugestoes, registros, perguntas, respostas, id_cliente) VALUES ('Trocar a lâmpada do farol', 'Farol apagado', 'As luzes de freio estão funcionando?', 'Não', 5);
INSERT INTO t_historico (sugestoes, registros, perguntas, respostas, id_cliente) VALUES ('Revisar a suspensão', 'Carro apresentando vibrações', 'Vibrações no volante?', 'Sim', 6);
INSERT INTO t_historico (sugestoes, registros, perguntas, respostas, id_cliente) VALUES ('Trocar o filtro de combustível', 'Carro parando frequentemente', 'O carro está parando frequentemente?', 'Sim', 7);
INSERT INTO t_historico (sugestoes, registros, perguntas, respostas, id_cliente) VALUES ('Reparar a pintura', 'Pintura descascando', 'Pintura do carro está descascando?', 'Sim', 8);
INSERT INTO t_historico (sugestoes, registros, perguntas, respostas, id_cliente) VALUES ('Verificar o sistema de travas', 'Portas não estavam travando', 'As portas estão travando?', 'Não', 9);
INSERT INTO t_historico (sugestoes, registros, perguntas, respostas, id_cliente) VALUES ('Trocar o sensor de óleo', 'Sensor apresentando falhas', 'Escapamento está funcionando?', 'Sim', 10);
INSERT INTO t_historico (sugestoes, registros, perguntas, respostas, id_cliente) VALUES ('Verificar o alternador', 'Carro não estava pegando', 'Bateria está carregando?', 'Não', 11);
INSERT INTO t_historico (sugestoes, registros, perguntas, respostas, id_cliente) VALUES ('Trocar a válvula termostática', 'Sistema de arrefecimento apresentando problemas', 'O carro está superaquecendo?', 'Sim', 12);
INSERT INTO t_historico (sugestoes, registros, perguntas, respostas, id_cliente) VALUES ('Verificar a buzina', 'Buzina não estava funcionando', 'Buzina está funcionando?', 'Não', 13);
INSERT INTO t_historico (sugestoes, registros, perguntas, respostas, id_cliente) VALUES ('Verificar o balanceamento', 'Carro apresentando vibrações', 'Vibrações no volante?', 'Sim', 14);
INSERT INTO t_historico (sugestoes, registros, perguntas, respostas, id_cliente) VALUES ('Trocar as pastilhas de freio', 'Freios estavam barulhentos', 'Os freios estão funcionando?', 'Não', 15);
INSERT INTO t_historico (sugestoes, registros, perguntas, respostas, id_cliente) VALUES ('Trocar a mangueira do radiador', 'Mangueira apresentando vazamento', 'O motor está superaquecendo?', 'Sim', 16);
INSERT INTO t_historico (sugestoes, registros, perguntas, respostas, id_cliente) VALUES ('Verificar os amortecedores', 'Suspensão apresentando problemas', 'A suspensão está fazendo barulho?', 'Sim', 17);
INSERT INTO t_historico (sugestoes, registros, perguntas, respostas, id_cliente) VALUES ('Verificar a direção', 'Direção pesada', 'A direção está pesada?', 'Sim', 18);
INSERT INTO t_historico (sugestoes, registros, perguntas, respostas, id_cliente) VALUES ('Ajustar os faróis', 'Faróis desregulados', 'Os faróis estão regulados?', 'Não', 19);
INSERT INTO t_historico (sugestoes, registros, perguntas, respostas, id_cliente) VALUES ('Trocar a embreagem', 'Embreagem não estava funcionando', 'A embreagem está funcionando?', 'Não', 20);

//INSERINDO DADOS NA TABELA ORÇAMENTO
INSERT INTO t_orcamento (datao, valor, id_veiculo) VALUES (TO_DATE('2024-06-05', 'YYYY-MM-DD'), 1450.00, 1);
INSERT INTO t_orcamento (datao, valor, id_veiculo) VALUES (TO_DATE('2024-06-06', 'YYYY-MM-DD'), 1200.00, 2);
INSERT INTO t_orcamento (datao, valor, id_veiculo) VALUES (TO_DATE('2024-06-07', 'YYYY-MM-DD'), 800.00, 3);
INSERT INTO t_orcamento (datao, valor, id_veiculo) VALUES (TO_DATE('2024-06-08', 'YYYY-MM-DD'), 950.00, 4);
INSERT INTO t_orcamento (datao, valor, id_veiculo) VALUES (TO_DATE('2024-06-09', 'YYYY-MM-DD'), 2000.00, 5);
INSERT INTO t_orcamento (datao, valor, id_veiculo) VALUES (TO_DATE('2024-06-10', 'YYYY-MM-DD'), 1750.00, 6);
INSERT INTO t_orcamento (datao, valor, id_veiculo) VALUES (TO_DATE('2024-06-11', 'YYYY-MM-DD'), 1600.00, 7);
INSERT INTO t_orcamento (datao, valor, id_veiculo) VALUES (TO_DATE('2024-06-12', 'YYYY-MM-DD'), 1350.00, 8);
INSERT INTO t_orcamento (datao, valor, id_veiculo) VALUES (TO_DATE('2024-06-13', 'YYYY-MM-DD'), 1100.00, 9);
INSERT INTO t_orcamento (datao, valor, id_veiculo) VALUES (TO_DATE('2024-06-14', 'YYYY-MM-DD'), 1450.00, 10);
INSERT INTO t_orcamento (datao, valor, id_veiculo) VALUES (TO_DATE('2024-06-15', 'YYYY-MM-DD'), 900.00, 11);
INSERT INTO t_orcamento (datao, valor, id_veiculo) VALUES (TO_DATE('2024-06-16', 'YYYY-MM-DD'), 1700.00, 12);
INSERT INTO t_orcamento (datao, valor, id_veiculo) VALUES (TO_DATE('2024-06-17', 'YYYY-MM-DD'), 1250.00, 13);
INSERT INTO t_orcamento (datao, valor, id_veiculo) VALUES (TO_DATE('2024-06-18', 'YYYY-MM-DD'), 1300.00, 14);
INSERT INTO t_orcamento (datao, valor, id_veiculo) VALUES (TO_DATE('2024-06-19', 'YYYY-MM-DD'), 1150.00, 15);
INSERT INTO t_orcamento (datao, valor, id_veiculo) VALUES (TO_DATE('2024-06-20', 'YYYY-MM-DD'), 1900.00, 16);
INSERT INTO t_orcamento (datao, valor, id_veiculo) VALUES (TO_DATE('2024-06-21', 'YYYY-MM-DD'), 1400.00, 17);
INSERT INTO t_orcamento (datao, valor, id_veiculo) VALUES (TO_DATE('2024-06-22', 'YYYY-MM-DD'), 1150.00, 18);
INSERT INTO t_orcamento (datao, valor, id_veiculo) VALUES (TO_DATE('2024-06-23', 'YYYY-MM-DD'), 1250.00, 19);
INSERT INTO t_orcamento (datao, valor, id_veiculo) VALUES (TO_DATE('2024-06-24', 'YYYY-MM-DD'), 850.00, 20);


//IMPLEMENTAÇÕES

//1. Relatório utilizando classificação de dados
//Relatório de Diagnósticos por Cliente
// Ele deve retornar o nome do cliente junto a diagnosticos associados a ele
SELECT t_cliente.nome_cliente, COUNT(t_diagnostico.id_diagnostico) AS total_diagnosticos
FROM t_cliente
JOIN t_veiculo ON t_cliente.id_cliente = t_veiculo.id_cliente
JOIN t_diagnostico ON t_veiculo.id_veiculo = t_diagnostico.id_veiculo
GROUP BY t_cliente.nome_cliente
ORDER BY total_diagnosticos DESC;

//Relatório de Orçamentos por Veículo
//Retorna a contagem de modelos do mesmo tipo
SELECT t_veiculo.modelo, COUNT(t_orcamento.id_orcamento) AS total_orcamentos
FROM t_veiculo
JOIN t_orcamento ON t_veiculo.id_veiculo = t_orcamento.id_veiculo
GROUP BY t_veiculo.modelo
ORDER BY total_orcamentos DESC;



//2. Relatório utilizando alguma função do tipo numérica simples
//Valor Total de Orçamentos
//Rertorna o valor total dos orçamentos
SELECT SUM(valor) AS valor_total_orcamentos
FROM t_orcamento;

//Média de Valores de Peças
//Retorna a média do valor das peças
SELECT AVG(valor_peca) AS media_valor_pecas
FROM t_pecas;



//3. Relatório utilizando alguma função de grupo
//Contagem de Clientes por Estado
//Este comando mostra quantos clientes temos em cada estado
SELECT t_endereco.estado, COUNT(t_cliente.id_cliente) AS total_clientes
FROM t_cliente
JOIN t_endereco ON t_cliente.id_cliente = t_endereco.id_cliente
GROUP BY t_endereco.estado;

//Total de Peças por Diagnóstico
//Aqui é possivel ver quantas peças estão em cada diagnóstico
SELECT t_diagnostico.perguntas, COUNT(t_pecas.id_pecas) AS total_pecas
FROM t_diagnostico
JOIN t_pecas ON t_diagnostico.id_diagnostico = t_pecas.id_diagnostico
GROUP BY t_diagnostico.perguntas;



//4. Relatório utilizando subconsulta
//Clientes com Orçamento Acima da Média
// Aqui é possivel verificar clientes acima da média de orçamento
SELECT t_cliente.nome_cliente
FROM t_cliente
WHERE t_cliente.id_cliente IN (
    SELECT t_veiculo.id_cliente
    FROM t_veiculo
    JOIN t_orcamento ON t_veiculo.id_veiculo = t_orcamento.id_veiculo
    WHERE t_orcamento.valor > (
        SELECT AVG(valor) FROM t_orcamento
    )
);

//Veículos que Tiveram Diagnósticos Específicos
// Esse trecho podemos verificar carros que tiveram 'motor' em seu diagnostico
SELECT t_veiculo.modelo
FROM t_veiculo
WHERE t_veiculo.id_veiculo IN (
    SELECT t_diagnostico.id_veiculo
    FROM t_diagnostico
    WHERE t_diagnostico.perguntas LIKE '%motor%'
);



//5. Relatório utilizando junção de tabelas
//Orçamentos com Informações do Cliente e Veículo
//Esse codigo traz informações sobre os orçamentos.
SELECT t_cliente.nome_cliente, t_veiculo.modelo, t_orcamento.valor, t_orcamento.datao
FROM t_orcamento
JOIN t_veiculo ON t_orcamento.id_veiculo = t_veiculo.id_veiculo
JOIN t_cliente ON t_veiculo.id_cliente = t_cliente.id_cliente;


//Diagnósticos e suas Peças Associadas
//Essa consulta retorna uma lista que associa diagnósticos às peças relacionadas, incluindo as perguntas sobre o diagnóstico
SELECT t_diagnostico.perguntas, t_pecas.nome_da_peca, t_pecas.valor_peca
FROM t_diagnostico
JOIN t_pecas ON t_diagnostico.id_diagnostico = t_pecas.id_diagnostico;


